apiVersion: apps/v1
kind: Deployment
metadata:
  name: dovecot
  namespace: {{ .Values.namespace }}
  labels:
    app: dovecot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dovecot
  template:
    metadata:
      labels:
        app: dovecot
    spec:
      containers:
        - name: dovecot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          ports:
            - containerPort: {{ .Values.protocols.imap.port }}
              name: imap
            - containerPort: {{ .Values.protocols.pop3.port }}
              name: pop3
            - containerPort: {{ .Values.protocols.lmtp.port }}
              name: lmtp
            - containerPort: {{ .Values.protocols.managesieve.port }}
              name: managesieve
          volumeMounts:
            - name: dovecot-data
              mountPath: {{ .Values.mailRoot }}
            - name: dovecot-conf
              mountPath: /etc/dovecot/dovecot.conf
              subPath: dovecot.conf
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: dovecot-data
          persistentVolumeClaim:
            claimName: dovecot-data
        - name: dovecot-conf
          configMap:
            name: dovecot-conf
