apiVersion: v1
kind: Service
metadata:
  name: dovecot
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: dovecot
  ports:
    - name: imap
      port: {{ .Values.protocols.imap.port }}
    - name: pop3
      port: {{ .Values.protocols.pop3.port }}
    - name: lmtp
      port: {{ .Values.protocols.lmtp.port }}
    - name: managesieve
      port: {{ .Values.protocols.managesieve.port }}
